[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/caoimhebyrne/petal"
version = "0.1.0"

[workspace.dependencies]
petal-ast = { path = "crates/petal-ast" }
petal-diagnostic = { path = "crates/petal-diagnostic" }
petal-lexer = { path = "crates/petal-lexer" }
petal-span = { path = "crates/petal-span" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
must_use_candidate = "allow"
