use std::{
    collections::HashMap,
    io::Write,
    path::PathBuf,
    process::{
        Command,
        Stdio,
    },
};

use crate::{
    ast::{
        expression::binary_operation::BinaryOperator,
        statement::function_declaration::DeclarationModifier,
    },
    backend::c::writer::Writer,
    typed_ast::{
        Expression,
        Function,
        FunctionKey,
        Program,
        Statement,
        StatementKind,
        r#type::{
            Type,
            db::{
                DefinedTypeId,
                TypeDb,
                TypeId,
            },
            defined::{
                DefinedTypeKind,
                Structure,
            },
        },
        visitor::{
            ProgramVisitor,
            walk_function,
            walk_program,
            walk_statement,
        },
    },
};

mod writer;

pub struct CBackend<'db> {
    /// The names of functions within the program being visited.
    function_names: HashMap<FunctionKey, String>,

    /// The [`TypeDb`] containing the types used by this program.
    type_db: &'db TypeDb,

    /// The writer to use when emitting C code.
    writer: Writer,
}

impl<'db> CBackend<'db> {
    /// Visits the [`Program`] owned by this [`CBackend`].
    pub fn visit(program: &'db mut Program) -> Self {
        let mut visitor = CBackend::new(&program.type_db);

        visitor.writer.append_line("#include <stdbool.h>");
        visitor.writer.append_line("#include <stdint.h>");
        visitor.writer.append_line("#include <stdio.h>");
        visitor.writer.append_line("#include <stdlib.h>");
        visitor.writer.append_line("#include <string.h>");
        visitor.writer.append_line("#include <unistd.h>");

        for (function_key, function) in &program.functions {
            visitor.function_names.insert(*function_key, Self::create_function_c_name(&program.type_db, function));
        }

        for defined_type_id in program.type_db.iter_defined_types() {
            visitor.writer.append_line("");
            visitor.visit_defined_type_id(*defined_type_id);
        }

        walk_program(&mut visitor, &mut program.functions);
        visitor
    }

    /// Returns the code that has been generated by this [`CBackend`].
    pub fn get_code(&self) -> &str {
        &self.writer.inner
    }

    /// Compiles C code into a binary.
    pub fn emit_binary(&self, executable_file_path: &PathBuf) -> Result<(), String> {
        let mut child = Command::new("cc")
            // Tell the compiler that the stdin contains C code.
            .args(["-x", "c"])
            .arg("-o")
            .arg(executable_file_path)
            // Tell the compiler to read from stdin.
            .arg("-")
            .stdin(Stdio::piped())
            .spawn()
            .map_err(|e| e.to_string())?;

        child
            .stdin
            .as_mut()
            .ok_or("Failed to open stdin to compiler process".to_string())?
            .write_all(self.writer.inner.as_bytes())
            .map_err(|e| e.to_string())?;

        let status = child.wait().map_err(|e| e.to_string())?;

        if !status.success() {
            return Err(format!("C compiler had {status}"));
        }

        Ok(())
    }

    /// Creates a new [`CBackend`] with the provided [`TypeDb`].
    fn new(type_db: &'db TypeDb) -> Self {
        Self { function_names: HashMap::default(), type_db, writer: Writer::default() }
    }

    /// Takes a mutable reference to [`self`], then:
    ///
    /// - increases its [`Writer`]'s indentation level,
    /// - executes the code in the provided `func`, passing the mutable self,
    /// - and decreases the [`Writer`]'s indentation level.
    fn with_writer_indent<F, R>(&mut self, func: F) -> R
    where
        F: FnOnce(&mut Self) -> R,
    {
        self.writer.increase_indentation();
        let result = func(self);
        self.writer.decrease_indentation();

        result
    }

    /// Visits the [`DefinedType`] referenced by the provided [`DefinedTypeId`].
    fn visit_defined_type_id(&mut self, defined_type_id: DefinedTypeId) {
        let defined_type = self.type_db.get_defined_type(defined_type_id);
        self.visit_defined_type_kind(&Self::get_defined_type_c_name(self.type_db, defined_type_id), &defined_type.kind);
    }

    /// Visits the provided [`DefinedTypeKind`].
    fn visit_defined_type_kind(&mut self, name: &str, defined_type_kind: &DefinedTypeKind) {
        match defined_type_kind {
            DefinedTypeKind::Structure(structure) => self.visit_structure_type(name, structure),
        }
    }

    /// Visits the provided [`Structure`] type.
    fn visit_structure_type(&mut self, name: &str, structure: &Structure) {
        self.writer.append_line("typedef struct {");

        self.with_writer_indent(|this| {
            for field in &structure.fields {
                let field_type = CBackend::get_type_c_name(this.type_db, field.type_id);
                let field_name = &field.name;

                this.writer.append_line(&format!("{field_type} {field_name};"));
            }
        });

        self.writer.append_line(&format!("}} {name};"));
    }

    /// Gets the C name for a [`Function`] by its [`FunctionKey`].
    fn get_function_c_name_by_key(&self, function_key: &FunctionKey) -> &str {
        self.function_names.get(function_key).expect("self.function_names.get() should return `Some(_)`")
    }

    /// Gets the C name for a [`Function`].
    fn create_function_c_name(type_db: &TypeDb, function: &Function) -> String {
        if function.name == "main" || function.modifiers.contains(&DeclarationModifier::Extern) {
            return function.name.clone();
        }

        let module_id = function.span.module_id;

        let name = &function.name;

        let parameter_types = function
            .parameters
            .iter()
            .map(|it| it.type_id)
            .map(|it| Self::get_type_identifier_name(type_db, it))
            .collect::<Vec<_>>();

        let return_type = Self::get_type_identifier_name(type_db, function.return_type_id);

        format!(
            "petal_mod_{module_id}_func_{name}_{return_type}{}",
            if parameter_types.is_empty() { String::new() } else { format!("_{}", parameter_types.join("_")) }
        )
    }

    /// Gets the C name for a [`Type`] from its [`TypeId`].
    fn get_type_c_name(type_db: &TypeDb, type_id: TypeId) -> String {
        let ty = type_db.get_type(type_id);
        match ty {
            Type::Boolean => "bool".to_string(),

            Type::Defined(defined_type_id) => Self::get_defined_type_c_name(type_db, *defined_type_id),

            Type::Reference(inner_type_id) => {
                format!("{}*", Self::get_type_c_name(type_db, *inner_type_id))
            }

            Type::SignedInteger(bits) => format!("int{bits}_t"),

            Type::UnsignedInteger(bits) => format!("uint{bits}_t"),

            Type::Void => "void".to_string(),
        }
    }

    /// Escapes the provided string so that it can be embedded within a C string literal.
    ///
    /// The values held by string literals have already had their escape sequences decoded by the
    /// lexer, so they must be re-escaped before being written back out as C source code.
    fn escape_c_string(value: &str) -> String {
        let mut escaped = String::with_capacity(value.len());

        for byte in value.bytes() {
            match byte {
                b'"' => escaped.push_str("\\\""),
                b'\\' => escaped.push_str("\\\\"),
                b'\n' => escaped.push_str("\\n"),
                b'\r' => escaped.push_str("\\r"),
                b'\t' => escaped.push_str("\\t"),

                // Printable ASCII can be written out as-is.
                0x20..=0x7e => escaped.push(byte as char),

                // Everything else (including the individual bytes of any multi-byte UTF-8 sequence)
                // is written as a three digit octal escape. Octal escapes are used over hexadecimal
                // ones as C limits them to three digits, meaning that they can never be extended by
                // a digit which happens to follow them in the string.
                _ => escaped.push_str(&format!("\\{byte:03o}")),
            }
        }

        escaped
    }

    /// Gets the C name for a [`DefinedType`] from its [`DefinedTypeId`].
    fn get_defined_type_c_name(type_db: &TypeDb, defined_type_id: DefinedTypeId) -> String {
        let defined_type = type_db.get_defined_type(defined_type_id);
        let module_id = defined_type.span.module_id;
        let type_name = &defined_type.name;

        format!("ptl_mod_{module_id}_type_{defined_type_id}_{type_name}")
    }

    /// Gets an identifier-friendly name for a [`Type`] from its [`TypeId`].
    fn get_type_identifier_name(type_db: &TypeDb, type_id: TypeId) -> String {
        let ty = type_db.get_type(type_id);
        match ty {
            Type::Boolean => "boolean".to_string(),

            Type::Defined(defined_type_id) => {
                let defined_type = type_db.get_defined_type(*defined_type_id);
                defined_type.name.clone()
            }

            Type::Reference(inner_type_id) => {
                let inner_type = Self::get_type_identifier_name(type_db, *inner_type_id);
                format!("Reference{inner_type}")
            }

            Type::SignedInteger(bits) => {
                format!("i{bits}")
            }

            Type::UnsignedInteger(bits) => {
                format!("u{bits}")
            }

            Type::Void => "void".to_string(),
        }
    }
}

impl ProgramVisitor for CBackend<'_> {
    type Expr = String;

    fn default_expr_result() -> Self::Expr {
        "/* todo */".to_string()
    }

    fn visit_function(&mut self, function_key: &FunctionKey, function: &mut Function) {
        if function.modifiers.contains(&DeclarationModifier::Extern) {
            return;
        }

        self.writer.append_line("");

        let return_type = Self::get_type_c_name(self.type_db, function.return_type_id);
        let function_name = self.get_function_c_name_by_key(function_key);

        let parameters = function
            .parameters
            .iter()
            .map(|it| format!("{} {}", Self::get_type_c_name(self.type_db, it.type_id), it.name))
            .collect::<Vec<String>>()
            .join(", ");

        self.writer.append_line(&format!("{return_type} {function_name}({parameters}) {{"));
        self.with_writer_indent(|this| {
            walk_function(this, function);
        });
        self.writer.append_line("}");
    }

    fn visit_statement(&mut self, statement: &mut Statement) {
        self.writer.append_indentation_string();
        walk_statement(self, statement);

        if !matches!(statement.kind, StatementKind::Conditional { .. }) {
            self.writer.append(";\n");
        }
    }

    fn visit_statement_conditional(
        &mut self,
        condition: &mut Expression,
        then_block: &mut Vec<Statement>,
        else_block: &mut Vec<Statement>,
    ) {
        let condition = self.visit_expression(condition);
        self.writer.append(&format!("if ({condition}) {{\n"));

        self.with_writer_indent(|this| {
            for statement in then_block {
                this.visit_statement(statement);
            }
        });

        self.writer.append_line("} else {");

        self.with_writer_indent(|this| {
            for statement in else_block {
                this.visit_statement(statement);
            }
        });

        self.writer.append_line("}");
    }

    fn visit_statement_function_call(
        &mut self,
        function_key: &FunctionKey,
        arguments: &mut [Expression],
        type_id: &mut TypeId,
    ) {
        let function_call = &self.visit_expression_function_call(function_key, arguments, type_id);
        self.writer.append(function_call);
    }

    fn visit_statement_reference_value_assignment(&mut self, target: &mut Expression, value: &mut Expression) {
        let target = self.visit_expression(target);
        let value = self.visit_expression(value);

        self.writer.append(&format!("*({target}) = {value}"));
    }

    fn visit_statement_return(&mut self, value: Option<&mut Expression>) {
        if let Some(value) = value.map(|it| self.visit_expression(it)) {
            self.writer.append(&format!("return {value}"));
        } else {
            self.writer.append("return");
        }
    }

    fn visit_expression_string_literal(&mut self, value: &mut String) -> Self::Expr {
        // TODO: the string literal expression will be removed later
        let defined_type_id = self
            .type_db
            .find_defined_type("CompileTimeStr", &[])
            .expect("self.type_db.find_defined_type(\"CompileTimeStr\")");

        format!(
            "({}) {{ .data = \"{}\", .length = {} }}",
            Self::get_defined_type_c_name(self.type_db, defined_type_id),
            Self::escape_c_string(value),
            value.len()
        )
    }

    fn visit_statement_structure_field_assignment(
        &mut self,
        target: &mut Expression,
        field_index: &mut usize,
        value: &mut Expression,
    ) {
        let Type::Defined(defined_type_id) = self.type_db.get_type(target.type_id) else { unreachable!() };
        let DefinedTypeKind::Structure(structure) = &self.type_db.get_defined_type(*defined_type_id).kind;

        let field_name = &structure.fields[*field_index].name;
        let target = self.visit_expression(target);
        let value = self.visit_expression(value);

        self.writer.append(&format!("({target}).{field_name} = {value}"));
    }

    fn visit_statement_variable_assignment(
        &mut self,
        name: &str,
        value: &mut Expression,
        _variable_type_id: &mut TypeId,
    ) {
        let value = self.visit_expression(value);
        self.writer.append(&format!("{name} = {value}"));
    }

    fn visit_statement_variable_declaration(&mut self, name: &str, value: &mut Expression, type_id: &mut TypeId) {
        let variable_type = Self::get_type_c_name(self.type_db, *type_id);
        let value = self.visit_expression(value);

        self.writer.append(&format!("{variable_type} {name} = {value}"));
    }

    fn visit_expression_binary_operation(
        &mut self,
        left: &mut Expression,
        right: &mut Expression,
        operator: &mut BinaryOperator,
        _type_id: &mut TypeId,
    ) -> Self::Expr {
        let left = self.visit_expression(left);
        let right = self.visit_expression(right);
        let operator = match operator {
            BinaryOperator::Add => "+",
            BinaryOperator::Divide => "/",
            BinaryOperator::Equals => "==",
            BinaryOperator::Multiply => "*",
            BinaryOperator::NotEquals => "!=",
            BinaryOperator::Subtract => "-",
        };

        format!("{left} {operator} {right}")
    }

    fn visit_expression_boolean_literal(&mut self, value: &mut bool) -> Self::Expr {
        value.to_string()
    }

    fn visit_expression_dereference(&mut self, reference: &mut Expression) -> Self::Expr {
        let reference = self.visit_expression(reference);
        format!("*({reference})")
    }

    fn visit_expression_function_call(
        &mut self,
        function_key: &FunctionKey,
        arguments: &mut [Expression],
        _type_id: &mut TypeId,
    ) -> Self::Expr {
        let arguments = arguments.iter_mut().map(|it| self.visit_expression(it)).collect::<Vec<_>>().join(", ");
        let name = self.get_function_c_name_by_key(function_key);

        format!("{name}({arguments})")
    }

    fn visit_expression_number_literal(&mut self, value: &mut f64, _type_id: &mut TypeId) -> Self::Expr {
        value.to_string()
    }

    fn visit_expression_reference(&mut self, value: &mut Expression) -> Self::Expr {
        let value = self.visit_expression(value);
        format!("&({value})")
    }

    fn visit_expression_structure_field_reference(
        &mut self,
        target: &mut Expression,
        field_index: &mut usize,
    ) -> Self::Expr {
        let Type::Defined(defined_type_id) = self.type_db.get_type(target.type_id) else { unreachable!() };
        let DefinedTypeKind::Structure(structure) = &self.type_db.get_defined_type(*defined_type_id).kind;

        let field_name = &structure.fields[*field_index].name;
        let target = self.visit_expression(target);

        format!("({target}).{field_name}")
    }

    fn visit_expression_structure_initialization(
        &mut self,
        field_values: &mut Vec<Expression>,
        type_id: &mut TypeId,
    ) -> Self::Expr {
        let Type::Defined(defined_type_id) = self.type_db.get_type(*type_id) else { unreachable!() };

        let struct_name = Self::get_defined_type_c_name(self.type_db, *defined_type_id);
        let field_values = field_values.iter_mut().map(|it| self.visit_expression(it)).collect::<Vec<_>>().join(", ");
        format!("({struct_name}) {{ {field_values} }}")
    }

    fn visit_expression_variable_reference(&mut self, variable_name: &mut str, _type_id: &mut TypeId) -> Self::Expr {
        variable_name.to_string()
    }
}
